version: '3.8'
services:
  app:
    container_name: sneakery-shop-be
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
